### ISSUE TITLE
Consider changing description from "Redis client" to "Valkey and Redis client"

### ISSUE THREAD

**Issue by lpil** [massivefermion/radish#2]
Hello!

The company that owns the name Redis are now using the name to refer to a non-open source version of the database. The open source line is now maintained by the Linux Foundation and is called Valkey.

https://github.com/valkey-io/valkey

It would be good to make clear that this library works with both, and to support open source :)

Thanks,
Louis

**Comment by massivefermion** [comment]
Hello
That makes sense, I'm just gonna update the deps and fix the warnings before publishing a new version with the updated description.
But I think I'm also going to add "and other compatible tools" or something like that in the end because I think there are more than one Redis forks at this point, e.g. https://docs.keydb.dev
